import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Navbar } from "@/components/navbar";
import { HeaderProvider } from "@/lib/header-context";
import { ThemeProvider } from "@/lib/theme-context";
import { Providers } from "@/app/providers";
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={jetbrainsMono.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ThemeProvider>
            <HeaderProvider>
              <SidebarProvider>
                <AppSidebar />
                <div className="flex flex-col w-full">
                  <Navbar />
                  <main className="flex-1 overflow-auto">{children}</main>
                </div>
              </SidebarProvider>
            </HeaderProvider>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
